import './globals.css';
import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/toaster';
import { Roboto } from 'next/font/google';
import { AuthContextProvider } from '@/context/AuthContext';
import ReactQueryProvider from '@/providers/ReactQueryProvider';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
});

export const metadata: Metadata = {
  title: 'Control',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReactQueryProvider>
          <AuthContextProvider>{children}</AuthContextProvider>
        </ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
